name         'lexkastro/easysquid'
version      '0.0.1'
source       'https://github.com/lexkastro/easysquid'
author       'Alex De Castro'
license      'MIT License'
summary      'Installs and congfigures squid proxy in an easy way.'
project_page 'https://github.com/lexkastro/easysquid'
dependency   'puppetlabs/concat', '2.x'
dependency   'puppetlabs/stdlib', '2.x'
